version: '3.5'
services:

   
# ============================================================================
# ============================================================================
#                           HELLO-HELYOS USER INTERFACE
# ============================================================================
# ============================================================================

  app:
    build: .
    ports:
      - 5174:5174

    networks:
            - control-tower-net
volumes:
  myapp:

networks:
    control-tower-net:
        name: control-tower-net
        external: true
